{% set version = "0.7.6" %}

package:
  name: ergocub-software-split
  version: {{ version }}

source:
  - url: https://github.com/icub-tech-iit/ergocub-software/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a8359034cee4f0c6aaef8852c9c75781e34c15d4976638429a0da3902638a30a

build:
  number: 0

outputs:
  - name: ergocub-models
    script: build_models.sh  # [unix]
    script: bld_models.bat  # [win]
    requirements:
      build:
        - cmake
        - pkg-config
        - ninja
        - multisheller

    test:
      commands:
        - test -f ${PREFIX}/share/ergoCub/robots/ergoCubSN002/model.urdf  # [unix]
        - if not exist %LIBRARY_PREFIX%\\share\\ergoCub\\robots\\ergoCubSN002\\model.urdf exit 1  # [win]

  - name: libergocub-software
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libergocub-software", max_pin='x.x.x') }}
      ignore_run_exports_from:
      # idyntree is just used for tests
        - idyntree
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        # YARP idl tools are used in this recipe
        - libyarp  # [build_platform != target_platform]
      host:
        - ycm-cmake-modules
        - libyarp
        - libopencv
        - idyntree
      run:
        - {{ pin_subpackage('ergocub-models', max_pin='x.x.x') }}

    test:
      commands:
        - test -f ${PREFIX}/lib/yarp/yarp_couplingXCubHandMk5.so  # [unix]
        - if not exist %LIBRARY_LIB%\\yarp\\yarp_couplingXCubHandMk5.dll exit 1  # [win]

  - name: ergocub-software
    requirements:
      run:
        - {{ pin_subpackage("libergocub-software", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/lib/yarp/yarp_couplingXCubHandMk5.so  # [unix]
        - if not exist %LIBRARY_LIB%\\yarp\\yarp_couplingXCubHandMk5.dll exit 1  # [win]


about:
  home: https://github.com/icub-tech-iit/ergocub-software
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Software and configuration files required to simulate and run the ergoCub humanoid robot.'
  description: |
    This feedstock builds the following packages:
      * `ergocub-models`: Depedency-free package that contains the `URDF` models of the different version of the `ergoCub` robot.
      * `libergocub-software`: Plugins and executables used for ergoCub simulations and for operating the ergoCub robot, it depends on `ergocub-models`.
      * `ergocub-models` : Meta-package that install all the software provided by the feedstock, i.e. `libergocub-software` and `ergocub-models`.


extra:
  feedstock-name: ergocub-software
  recipe-maintainers:
    - traversaro
